version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosec
    - gocritic
    - revive
    - ineffassign
    - unused
    - misspell

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-dirs:
    - .go
